### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by xiaomeyu** [logic-ng/LogicNG#1]
The program will throw an Out Of Memory error if the formula has many variables(e.g. more than 200 variables).
java.lang.OutOfMemoryError: Java heap space
    at java.util.LinkedHashMap.createEntry(Unknown Source)
    at java.util.HashMap.addEntry(Unknown Source)
    at java.util.LinkedHashMap.addEntry(Unknown Source)
    at java.util.HashMap.put(Unknown Source)
    at java.util.HashSet.add(Unknown Source)
    at org.logicng.formulas.FormulaFactory.addFormulaOr(FormulaFactory.java:900)
    at org.logicng.formulas.FormulaFactory.condenseOperandsOr(FormulaFactory.java:812)
    at org.logicng.formulas.FormulaFactory.constructOr(FormulaFactory.java:520)
    at org.logicng.formulas.FormulaFactory.or(FormulaFactory.java:477)
    at org.logicng.transformations.cnf.CNFFactorization.distribute(CNFFactorization.java:109)
    at org.logicng.transformations.cnf.CNFFactorization.distribute(CNFFactorization.java:106)
    at org.logicng.transformations.cnf.CNFFactorization.distribute(CNFFactorization.java:106)
    at org.logicng.transformations.cnf.CNFFactorization.apply(CNFFactorization.java:66)
    at org.logicng.transformations.cnf.CNFFactorization.apply(CNFFactorization.java:52)
    at org.logicng.formulas.Formula.transform(Formula.java:191)
    at org.logicng.formulas.Formula.cnf(Formula.java:182)
    at org.logicng.solvers.MiniGSat.add(MiniGat.java:154)
    at org.logicng.solvers.sat.Test.parseRules(Test.java:94)
    at org.logicng.solvers.sat.Test.testAssume(Test.java:66)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

**Comment by czengler** [comment]
From the stack trace it looks like you use CNF factorization to convert your formula to CNF.  Factorization has a worst case exponential space complexity - so if your formula has 200 variables it is quite possible, that this algorithm does simply not work.

You should instead try to convert your formula to CNF with the Tseitin or the Plaisted/Greenbaum algorithm.  These algorithms introduce new variables but therefore are guaranteed to work on large formulas.

This however is not an issue with the library per se.  The factorization algorithm is only applicable for small formulas.

**Comment by xiaomeyu** [comment]
It works.
Thanks a lot.

**Comment by eleanore0102** [comment]
Hi, I have encountered the same issue, but since the CNF conversion will be used as input to other services, I cannot use Tseitin or Plaisted etc. Do you have any other suggestions? Thanks!

**Comment by rouven-walter** [comment]
@eleanore0102 Is it necessary for the other service to have an equivalent CNF as input? Or, is an [equisatisfiable](https://en.wikipedia.org/wiki/Equisatisfiability) CNF sufficient? If equisatisfiable is sufficient, then you can still use the Tseitin or Plaisted/Greenbaum transformation to convert your formula into an equisatisfiable CNF.

**Comment by SHildebrandt** [comment]
Hi @eleanore0102 / @yiyijin , assuming you have given LogicNG "enough" heap space, it seems like the resulting CNF is just too large. So the question is also if such a large CNF could even be handled by the other service. Do you have control over the other service? Maybe there is a better way than the CNF conversion.
Also, it could help us if you could share the formula or some statistics of it (number of variables, number of internal nodes, etc)?

**Comment by yiyijin** [comment]
@SHildebrandt yes, you made the write the point! even the CNF conversion is done by factorization, the other service will not be able to consume it. As for sharing statistics, I will need to check with Company policies. Thanks a lot for the help.

**Comment by czengler** [comment]
Just to clarify: at some point the CNF of a formula without the introduction of auxiliary variables can get too large (indeed exponential).  So if your input formula is too large, the CNF transformation with the factorization method will not be feasible.

Like @rouven-walter and @SHildebrandt said: you could use one of the other methods for CNF conversion which introduce helper variables (you can even configure the default CNF method in the formula factory).  Another idea would be to play around and experiment with BDDs.  If you can transform your formula to a BDD with the BDD package in LogicNG (since 1.4) you would be able to produce a CNF of the formula without introducing new variables.  To generate the BDD you have to experiment with the size of the number of nodes and the node cache - but perhaps this could work in your case.

**Comment by arfarhadi** [comment]
> Just to clarify: at some point the CNF of a formula without the introduction of auxiliary variables can get too large (indeed exponential). So if your input formula is too large, the CNF transformation with the factorization method will not be feasible.
> 
> Like @rouven-walter and @SHildebrandt said: you could use one of the other methods for CNF conversion which introduce helper variables (you can even configure the default CNF method in the formula factory). Another idea would be to play around and experiment with BDDs. If you can transform your formula to a BDD with the BDD package in LogicNG (since 1.4) you would be able to produce a CNF of the formula without introducing new variables. To generate the BDD you have to experiment with the size of the number of nodes and the node cache - but perhaps this could work in your case.

Dear Dr @czengler as you mentioned above when I run the following code :
public String bddCnfSolverTest(String bmcFormula) throws ParserException{
	final FormulaFactory f = new FormulaFactory();
	final SATSolver miniSat = MiniSat.miniSat(f);
	final Formula formula = f.parse(bmcFormula);
	final BDD bddNoOrder = formula.bdd();
	miniSat.add(bddNoOrder.cnf());
	miniSat.sat();
	
	final Assignment model = miniSat.model();
	if (model == null) {
		return "no solution";
	}
	
	String result = "";
	for (Variable v : model.formula(f).variables()) {
		result += v.name() +":=" + v.evaluate(model)+"; ";
	}
	return result;
}
where its argument bmcFormula is a formula with 96 Boolean variables in the following file:
[bmcFormula96.txt](https://github.com/logic-ng/LogicNG/files/8007890/bmcFormula96.txt)

I got the following error:
java.lang.OutOfMemoryError: Java heap space
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.nodeResize(BDDKernel.java:603) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.makeNode(BDDKernel.java:493) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:395) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:394) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:393) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:402) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:401) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:401) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:401) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:402) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:402) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:402) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:394) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:398) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:397) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:398) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:397) ~[logicng-2.2.0.jar!/:2.2.0]
	at org.logicng.knowledgecompilation.bdds.jbuddy.BDDKernel.applyRec(BDDKernel.java:397) ~[logicng-2.2.0.jar!/:2.2.0]

But if I don't use BDD and call just

miniSat.add(formula);

then the solver works fine.

Regards,
Alireza
